### PR TITLE
V3.0.2

### PR DESCRIPTION
**Pull request by jwildfire**
Bug fixes for #50 and #56

### CODE REVIEW

**Comment by jwildfire** [comment]
Bug fixes committed and test cases created. 

- #50 - [broken in v3.0.1](https://rhoinc.github.io/viz-library/testing/aeexplorer-v3-0-2/issue50_broken.html) and [fixed](https://rhoinc.github.io/viz-library/testing/aeexplorer-v3-0-2/issue50_fixed.html)

- #56  - [broken in v3.0.1](https://rhoinc.github.io/viz-library/testing/aeexplorer-v3-0-2/issue56_broken.html) and [fixed](https://rhoinc.github.io/viz-library/testing/aeexplorer-v3-0-2/issue56_fixed.html)

**Comment by samussiah** [comment]
@jwildfire looks good but where are the test cases?

**Comment by jwildfire** [comment]
@samussiah Links are in my comment above.

**Comment by brittsikora** [comment]
- [x] (#50) Expected result: Error message makes logical sense and extra "6" has been removed
- [x] (#56) Expected result: Data displays in the rendered chart

**Pull request merged**
